name          'pauloconnor-graphite'
version       '0.1.0'
source        'github.com/pauloconnor/pauloconnor-graphite'
author        'pauloconnor'
license       'Apache 2.0'
summary       'Install and configure Graphite for multiple relays, caches and servers'
description   'Install and configure Graphite for multiple relays, caches and servers'
project_page  'https://github.com/pauloconnor/pauloconnor-graphite'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/logrotate'
dependency 'maestrodev/wget'
dependency 'puppetlabs/apache'